name: Test
description: "Runs Quilt’s test command on your workspace"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1
      name: Checkout

    - uses: actions/setup-node@v2
      name: Setup node.js and yarn
      with:
        node-version: 16.2.0
        cache: yarn

    - name: Yarn install
      run: yarn install --immutable
      shell: bash

    - uses: actions/cache@v2
      id: jest-cache
      name: Restore Jest cache
      with:
        path: .sewing-kit/temp/jest/cache
        key: ${{ runner.os }}-jest-v1-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-jest-v1-

    - name: Test
      run: yarn test
      shell: bash
