name: Test
description: "Runs Quilt’s test command on your workspace"
inputs:
  arguments:
    description: "Additional arguments to pass to sewing-kit’s test command"
    required: false
    default: ""
  command:
    description: "The command to run to start sewing-kit’s tests"
    required: false
    default: "node_modules/.bin/sewing-kit test"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      id: jest-cache
      name: Restore Jest cache
      with:
        path: .sewing-kit/temp/jest/cache
        key: ${{ runner.os }}-jest-v1-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-jest-v1-

    - name: Test
      run: ${{ inputs.command }} ${{ inputs.arguments }}
      shell: bash
